# fly.toml app configuration file generated for guptasiddhant on 2025-05-26T10:52:07+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'guptasiddhant'
primary_region = 'fra'

[build]

[mounts]
source = "guptasiddhant_www_data"
destination = "/app/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
