name: "CLI"
on:
  push:
    branches:
      - master
    paths:
      - "cli/**"
jobs:
  sanity-deploy:
    name: Deploy CLI
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
