name: "CLI"
on:
  push:
    branches:
      - master
    paths:
      - "cli/**"
jobs:
  sanity-deploy:
    name: Deploy CLI
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install -g @jsdevtools/npm-publish
      - run: yarn install
      - run: npm-publish --token ${{ secrets.NPM_AUTH_TOKEN }}
