name: "Deploy"
on:
  push:
    branches:
      - main
    paths-ignore:
      - apps/cli/**

env:
  DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read
    defaults:
      run:
        working-directory: "./apps/website"
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Setup PATH
        run: echo "/home/runner/.deno/bin" >> $GITHUB_PATH

      - name: Install deno
        run: curl -fsSL https://deno.land/install.sh | sh

      - name: Install deno deployctl
        run: deno install --allow-read --allow-write --allow-env --allow-net --allow-run --no-check -r -f https://deno.land/x/deploy/deployctl.ts

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build and deploy app
        run: yarn deploy
