name: "Sanity Server"
on:
  push:
    branches:
      - master
    paths:
      - "server/**"
jobs:
  sanity-deploy:
    name: Deploy Sanity
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install -g @sanity/cli
      - run: yarn install
      - run: SANITY_AUTH_TOKEN=${{ secrets.SANITY_AUTH_TOKEN }} sanity deploy
      # - run: SANITY_AUTH_TOKEN=${{ secrets.SANITY_AUTH_TOKEN }} sanity graphql deploy --playground
