name: "Sanity Server"
on:
  push:
    branches:
      - master
jobs:
  sanity-deploy:
    name: Deploy Sanity
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: deploy
