name: "Test"
on:
  push:
    branches:
      - main
    paths:
      - web
      - .github/workflows/test.yaml

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
