name: "Test"
on:
  push:
    branches:
      - main
    paths:
      - apps/remix/**
      - .github/workflows/test.yaml

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./apps/remix"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn workspace focus

      - name: Run tests
        run: yarn test:coverage
